# Clase 08 - Sistemas de ecuaciones lineales

In [1]:
import numpy as np
from matplotlib import pyplot as plt
from scipy import linalg

In [2]:
plt.style.use('seaborn-poster')

#formato de impresión de los números en los arreglos de Numpy
np.set_printoptions(formatter={'float': '{: .4f}'.format})

### Eliminación de Gauss

Este algoritmo de eliminación de Gauss usa la matriz aumentada y regresa la matriz triangular superior, el vector $\vec{b}$ modificado y el vector solución $\vec{x}$.  

Para eliminar los coeficientes bajo la fila $k$ con $k=1,2,\ldots,n-1$ hacemos

\begin{equation*}
\begin{aligned} 
A_{i j} & \leftarrow A_{i j}-\lambda A_{k j}, \quad j=k, k+1, \ldots, n \\ 
b_{i} & \leftarrow b_{i}-\lambda b_{k} 
\end{aligned}
\end{equation*}

donde $\lambda = A_{ik}/A_{kk}$. Si $A_{ik}$ es cero, no se realiza la transformación de la fila $i$.

In [3]:
def Gauss(A, b):
    n = len(b)
    Aug = np.concatenate((A,b.reshape(n,1)),axis=1)
    print (Aug)
    for k in range(n):
        for i in range(k+1,n):
            if Aug[i,k] != 0.0:
                lam = Aug[i,k]/Aug[k,k]
                print (i,k,lam)
                Aug[i,:] = Aug[i,:] - lam*Aug[k,:]
                print (Aug)
            
    x = np.zeros(n)
    for k in range(n-1,-1,-1):
        x[k] = (Aug[k,-1] - np.dot(Aug[k,k+1:n],x[k+1:n]))/Aug[k,k]
        
    return (Aug[:,:-1],Aug[:,-1],x)

Resolvamos el sistema de ecuaciones 

\begin{equation*}
\begin{aligned} 
4 x_{1}-2 x_{2}+x_{3} &=11 \\
-2 x_{1}+4 x_{2}-2 x_{3} &=-16 \\ 
x_{1}-2 x_{2}+4 x_{3} &=17 
\end{aligned}
\end{equation*}

In [4]:
A = np.array([[4,-2,1],[-2,4,-2],[1,-2,4]],dtype=np.double)
b = np.array([11,-16,17],dtype=np.double)
(U1,b1,x1) = Gauss(A,b)

[[ 4.0000 -2.0000  1.0000  11.0000]
 [-2.0000  4.0000 -2.0000 -16.0000]
 [ 1.0000 -2.0000  4.0000  17.0000]]
1 0 -0.5
[[ 4.0000 -2.0000  1.0000  11.0000]
 [ 0.0000  3.0000 -1.5000 -10.5000]
 [ 1.0000 -2.0000  4.0000  17.0000]]
2 0 0.25
[[ 4.0000 -2.0000  1.0000  11.0000]
 [ 0.0000  3.0000 -1.5000 -10.5000]
 [ 0.0000 -1.5000  3.7500  14.2500]]
2 1 -0.5
[[ 4.0000 -2.0000  1.0000  11.0000]
 [ 0.0000  3.0000 -1.5000 -10.5000]
 [ 0.0000  0.0000  3.0000  9.0000]]


In [5]:
print ('El vector solución es =',x1)

El vector solución es = [ 1.0000 -2.0000  3.0000]


In [6]:
print ('La matriz U es \n',U1)

La matriz U es 
 [[ 4.0000 -2.0000  1.0000]
 [ 0.0000  3.0000 -1.5000]
 [ 0.0000  0.0000  3.0000]]


In [7]:
# Verificamos la solución
print (np.dot(A,x1)-b)

[ 0.0000  0.0000  0.0000]


Ahora resolvamos el sistema de ecuaciones $A\vec{x}=\vec{b}$ con

\begin{equation*}
\mathbf{A}=\left[\begin{array}{rrrr}
1.44 & -0.36 & 5.52 & 0.00 \\ 
-0.36 & 10.33 & -7.78 & 0.00 \\ 
5.52 & -7.78 & 28.40 & 9.00 \\ 
0.00 & 0.00 & 9.00 & 61.00
\end{array}\right] \quad 
\mathbf{b}=\left[\begin{array}{r}
0.04 \\ 
-2.15 \\ 
0 \\ 
0.88
\end{array}\right]
\end{equation*}

In [8]:
A = np.array([[ 1.44, -0.36, 5.52, 0.0], [-0.36, 10.33, -7.78, 0.0],
              [ 5.52, -7.78, 28.40, 9.0], [ 0.0, 0.0, 9.0, 61.0]]) 
b = np.array([0.04, -2.15, 0.0, 0.88])

In [9]:
(U2,b2,x2) = Gauss(A,b)

[[ 1.4400 -0.3600  5.5200  0.0000  0.0400]
 [-0.3600  10.3300 -7.7800  0.0000 -2.1500]
 [ 5.5200 -7.7800  28.4000  9.0000  0.0000]
 [ 0.0000  0.0000  9.0000  61.0000  0.8800]]
1 0 -0.25
[[ 1.4400 -0.3600  5.5200  0.0000  0.0400]
 [ 0.0000  10.2400 -6.4000  0.0000 -2.1400]
 [ 5.5200 -7.7800  28.4000  9.0000  0.0000]
 [ 0.0000  0.0000  9.0000  61.0000  0.8800]]
2 0 3.833333333333333
[[ 1.4400 -0.3600  5.5200  0.0000  0.0400]
 [ 0.0000  10.2400 -6.4000  0.0000 -2.1400]
 [ 0.0000 -6.4000  7.2400  9.0000 -0.1533]
 [ 0.0000  0.0000  9.0000  61.0000  0.8800]]
2 1 -0.625
[[ 1.4400 -0.3600  5.5200  0.0000  0.0400]
 [ 0.0000  10.2400 -6.4000  0.0000 -2.1400]
 [ 0.0000  0.0000  3.2400  9.0000 -1.4908]
 [ 0.0000  0.0000  9.0000  61.0000  0.8800]]
3 2 2.777777777777776
[[ 1.4400 -0.3600  5.5200  0.0000  0.0400]
 [ 0.0000  10.2400 -6.4000  0.0000 -2.1400]
 [ 0.0000  0.0000  3.2400  9.0000 -1.4908]
 [ 0.0000  0.0000  0.0000  36.0000  5.0212]]


In [10]:
print ('El vector solución es =',x2)

El vector solución es = [ 3.0921 -0.7387 -0.8476  0.1395]


In [11]:
print ('La matriz U es \n',U2)

La matriz U es 
 [[ 1.4400 -0.3600  5.5200  0.0000]
 [ 0.0000  10.2400 -6.4000  0.0000]
 [ 0.0000  0.0000  3.2400  9.0000]
 [ 0.0000  0.0000  0.0000  36.0000]]


In [12]:
# Verifiquemos la solución
print (np.dot(A,x2)-b)

[ 0.0000  0.0000  0.0000 -0.0000]


Resolvamos este sistema de ecuaciones usando las rutinas solve de $\textit{Numpy}$ y $\textit{Scipy}$

In [13]:
print ('El vector solución es =',np.linalg.solve(A,b))

El vector solución es = [ 3.0921 -0.7387 -0.8476  0.1395]


In [14]:
print ('El vector solución es =',linalg.solve(A,b))

El vector solución es = [ 3.0921 -0.7387 -0.8476  0.1395]


### Eliminación de Gauss con pivote

Resolvamos el sistema de ecuacines $A\vec{x}=\vec{b}$ con

\begin{equation*}
\mathbf{A}=\left[\begin{array}{rrr}
1 & 1 & 1 \\
0 & 0 & 2 \\
0 & 1 & 1
\end{array}\right] 
\quad 
\mathbf{b}=\left[\begin{array}{r}
1 \\ 1 \\ 2
\end{array}\right]
\end{equation*}

In [15]:
E = np.array([[1.0, 1.0, 1.0],[0.0, 0.0, 2.0],[0.0, 1.0, 1.0]])
f = np.array([1.0, 1.0, 2.0])
(U3,b3,x3) = Gauss(E,f)

[[ 1.0000  1.0000  1.0000  1.0000]
 [ 0.0000  0.0000  2.0000  1.0000]
 [ 0.0000  1.0000  1.0000  2.0000]]
2 1 inf
[[ 1.0000  1.0000  1.0000  1.0000]
 [ 0.0000  0.0000  2.0000  1.0000]
 [ nan  nan -inf -inf]]


/Users/ameza/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in double_scalars
  
/Users/ameza/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: RuntimeWarning: invalid value encountered in multiply
  # Remove the CWD from sys.path while we load stuff.
/Users/ameza/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:15: RuntimeWarning: invalid value encountered in double_scalars
  from ipykernel import kernelapp as app


Para evitar errores con coeficientes nulos o muy pequeños, encontramos la fila $i>k$ con el mayor coeficiente en la columna $k$ e intercambiamos filas. Luego se procede como antes.

In [16]:
def GaussPivote(A,b):
    n = len(b)
    Aug = np.concatenate((A,b.reshape(n,1)),axis=1)
    print (Aug)
    for k in range(n):
        max_row = np.argmax(Aug[k:,k])
        if (max_row): #max_row es contado relativo a la fila k, es decir, max_row = 0 para k
            tmp = np.copy(Aug[k,:])
            Aug[k,:] = np.copy(Aug[k+max_row,:])
            Aug[k+max_row,:] = np.copy(tmp)
        for i in range(k+1,n):
            if Aug[i,k] != 0.0:
                lam = Aug[i,k]/Aug[k,k]
                print (i,k,lam)
                Aug[i,:] = Aug[i,:] - lam*Aug[k,:]
                print (Aug)
        
    x = np.zeros(n)
    for k in range(n-1,-1,-1):
        x[k] = (Aug[k,-1] - np.dot(Aug[k,k+1:n],x[k+1:n]))/Aug[k,k]
    
    return (Aug[:,:-1],Aug[:,-1],x)

In [17]:
(U3,b3,x3) = GaussPivote(E,f)

[[ 1.0000  1.0000  1.0000  1.0000]
 [ 0.0000  0.0000  2.0000  1.0000]
 [ 0.0000  1.0000  1.0000  2.0000]]


In [18]:
print ('El vector solución es =',x3)

El vector solución es = [-1.0000  1.5000  0.5000]


In [19]:
print ('La matriz U es \n',U3)

La matriz U es 
 [[ 1.0000  1.0000  1.0000]
 [ 0.0000  1.0000  1.0000]
 [ 0.0000  0.0000  2.0000]]


In [20]:
# Verifiquemos la solución
print (np.dot(E,x3)-f)

[ 0.0000  0.0000  0.0000]


Ahora volvamos a resolver el sistema de ecuaciones $A\vec{x}=\vec{b}$ con

\begin{equation*}
\mathbf{A}=\left[\begin{array}{rrrr}
1.44 & -0.36 & 5.52 & 0.00 \\ 
-0.36 & 10.33 & -7.78 & 0.00 \\ 
5.52 & -7.78 & 28.40 & 9.00 \\ 
0.00 & 0.00 & 9.00 & 61.00
\end{array}\right] \quad 
\mathbf{b}=\left[\begin{array}{r}
0.04 \\ 
-2.15 \\ 
0 \\ 
0.88
\end{array}\right]
\end{equation*}

In [21]:
A = np.array([[ 1.44, -0.36, 5.52, 0.0], [-0.36, 10.33, -7.78, 0.0],
              [ 5.52, -7.78, 28.40, 9.0], [ 0.0, 0.0, 9.0, 61.0]]) 
b = np.array([0.04, -2.15, 0.0, 0.88])

In [22]:
(U4,b4,x4) = GaussPivote(A,b)

[[ 1.4400 -0.3600  5.5200  0.0000  0.0400]
 [-0.3600  10.3300 -7.7800  0.0000 -2.1500]
 [ 5.5200 -7.7800  28.4000  9.0000  0.0000]
 [ 0.0000  0.0000  9.0000  61.0000  0.8800]]
1 0 -0.06521739130434782
[[ 5.5200 -7.7800  28.4000  9.0000  0.0000]
 [ 0.0000  9.8226 -5.9278  0.5870 -2.1500]
 [ 1.4400 -0.3600  5.5200  0.0000  0.0400]
 [ 0.0000  0.0000  9.0000  61.0000  0.8800]]
2 0 0.2608695652173913
[[ 5.5200 -7.7800  28.4000  9.0000  0.0000]
 [ 0.0000  9.8226 -5.9278  0.5870 -2.1500]
 [ 0.0000  1.6696 -1.8887 -2.3478  0.0400]
 [ 0.0000  0.0000  9.0000  61.0000  0.8800]]
2 1 0.16997167138810199
[[ 5.5200 -7.7800  28.4000  9.0000  0.0000]
 [ 0.0000  9.8226 -5.9278  0.5870 -2.1500]
 [ 0.0000  0.0000 -0.8811 -2.4476  0.4054]
 [ 0.0000  0.0000  9.0000  61.0000  0.8800]]
3 2 -0.09790368271954678
[[ 5.5200 -7.7800  28.4000  9.0000  0.0000]
 [ 0.0000  9.8226 -5.9278  0.5870 -2.1500]
 [ 0.0000  0.0000  9.0000  61.0000  0.8800]
 [ 0.0000  0.0000  0.0000  3.5245  0.4916]]


In [23]:
print ('El vector solución es =',x4)

El vector solución es = [ 3.0921 -0.7387 -0.8476  0.1395]


In [24]:
print ('La matriz U es \n',U4)

La matriz U es 
 [[ 5.5200 -7.7800  28.4000  9.0000]
 [ 0.0000  9.8226 -5.9278  0.5870]
 [ 0.0000  0.0000  9.0000  61.0000]
 [ 0.0000  0.0000  0.0000  3.5245]]


In [25]:
# Verifiquemos la solución
print (np.dot(A,x4)-b)

[ 0.0000  0.0000  0.0000 -0.0000]


In [26]:
print ('El vector solución es =',linalg.solve(A,b))

El vector solución es = [ 3.0921 -0.7387 -0.8476  0.1395]
