# Clase 09 - Sistemas de ecuaciones lineales II

In [1]:
import numpy as np
from matplotlib import pyplot as plt
from scipy import linalg

In [2]:
plt.style.use('seaborn-poster')

#formato de impresión de los números en los arreglos de Numpy
#np.set_printoptions(formatter={'float': '{: .4f}'.format})

### Descomposición LU

Toda matriz $\mathbf{A}$ puede ser escrita como el producto de una mtriz triangular inferior $\mathbf{L}$ y una matriz triangular superior $\mathbf{U}$, es decir, $\mathbf{A}=\mathbf{LU}$.

Esta descomposición no es única. Algunas de las descomposiciones más usadas son:

\begin{equation*}
\begin{array}{|l|l|}\hline \text { Nombre } & \text { Restricción } \\ \hline \hline \text { Doolittle } & L_{i i}=1, i=1,2, \ldots, n \\ \hline \text { Crout } & U_{i i}=1, i=1,2, \ldots, n \\ \hline \text { Choleski } & \mathbf{L}=\mathbf{U}^{T} \\ \hline\end{array}
\end{equation*}

Resolvamos el sistema de ecuaciones 

\begin{equation*}
\begin{aligned} 
4 x_{1}-2 x_{2}+x_{3} &=11 \\
-2 x_{1}+4 x_{2}-2 x_{3} &=-16 \\ 
x_{1}-2 x_{2}+4 x_{3} &=17 
\end{aligned}
\end{equation*}

La rutina lu_factor de $\textit{Scipy}$) implemente el método de Doolittle

In [3]:
A = np.array([[4,-2,1],[-2,4,-2],[1,-2,4]],dtype=np.double)
b = np.array([11,-16,17],dtype=np.double)

In [4]:
L,U = linalg.lu(A,permute_l=True)

In [5]:
print (L)

[[ 1.    0.    0.  ]
 [-0.5   1.    0.  ]
 [ 0.25 -0.5   1.  ]]


In [6]:
print (U)

[[ 4.  -2.   1. ]
 [ 0.   3.  -1.5]
 [ 0.   0.   3. ]]


In [7]:
lu, piv = linalg.lu_factor(A)

In [8]:
x = linalg.lu_solve((lu, piv), b)
print (x)

[ 1. -2.  3.]


Ahora resolvamos el sistema de ecuaciones $A\vec{x}=\vec{b}$ con

\begin{equation*}
\mathbf{A}=\left[\begin{array}{rrrr}
1.44 & -0.36 & 5.52 & 0.00 \\ 
-0.36 & 10.33 & -7.78 & 0.00 \\ 
5.52 & -7.78 & 28.40 & 9.00 \\ 
0.00 & 0.00 & 9.00 & 61.00
\end{array}\right] \quad 
\mathbf{b}=\left[\begin{array}{r}
0.04 \\ 
-2.15 \\ 
0 \\ 
0.88
\end{array}\right]
\end{equation*}

In [9]:
A = np.array([[ 1.44, -0.36, 5.52, 0.0], [-0.36, 10.33, -7.78, 0.0],
              [ 5.52, -7.78, 28.40, 9.0], [ 0.0, 0.0, 9.0, 61.0]]) 
b = np.array([0.04, -2.15, 0.0, 0.88])

In [10]:
lu, piv = linalg.lu_factor(A)
x = linalg.lu_solve((lu, piv), b)
print (x)

[ 3.09212567 -0.73871706 -0.8475723   0.13947788]


In [11]:
print (np.dot(A,x)-b)

[-1.74166237e-15  2.22044605e-15  0.00000000e+00  7.77156117e-16]


Resolvamos ahora el sistema de ecuaciones $A\vec{x}=\vec{b}$ con

\begin{equation*}
\mathbf{A}=\left[\begin{array}{rrr}
1 & 1 & 1 \\
0 & 0 & 2 \\
0 & 1 & 1
\end{array}\right] 
\quad 
\mathbf{b}=\left[\begin{array}{r}
1 \\ 1 \\ 2
\end{array}\right]
\end{equation*}

In [12]:
A = np.array([[1.0, 1.0, 1.0],[0.0, 0.0, 2.0],[0.0, 1.0, 1.0]])
b = np.array([1.0, 1.0, 2.0])

In [13]:
lu, piv = linalg.lu_factor(A)
x = linalg.lu_solve((lu, piv), b)
print (x)

[-1.   1.5  0.5]


In [14]:
print (np.dot(A,x)-b)

[0. 0. 0.]


### Descomposición de Cholesky

Consideremos la matriz 

\begin{equation*}
\mathbf{A}=\left[\begin{array}{rrrr}
6 & 3 & 4 & 8 \\
3 & 6 & 5 & 1 \\
4 & 5 & 10 & 7 \\
8 & 1 & 7 & 25 \\
\end{array}\right] 
\end{equation*}


In [15]:
A = np.array([[6, 3, 4, 8], [3, 6, 5, 1], [4, 5, 10, 7], [8, 1, 7, 25]])
L = linalg.cholesky(A, lower=True)
U = linalg.cholesky(A, lower=False)

In [16]:
print (L)

[[ 2.44948974  0.          0.          0.        ]
 [ 1.22474487  2.12132034  0.          0.        ]
 [ 1.63299316  1.41421356  2.30940108  0.        ]
 [ 3.26598632 -1.41421356  1.58771324  3.13249102]]


In [17]:
print (U)

[[ 2.44948974  1.22474487  1.63299316  3.26598632]
 [ 0.          2.12132034  1.41421356 -1.41421356]
 [ 0.          0.          2.30940108  1.58771324]
 [ 0.          0.          0.          3.13249102]]


In [18]:
print (np.dot(L,L.T)-A)

[[-8.8817842e-16  0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00 -8.8817842e-16  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00]]


In [19]:
print (np.dot(U.T,U)-A)

[[-8.8817842e-16  0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00 -8.8817842e-16  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00]]
